version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: dtq-mysql
    restart: always
    environment:
      - MY_SQL_ROOT_PASSWORD: rootpassword
      - MYSQL_DATABASE: distributed-task-queue
      - MYSQL_USER: fiyinfoluwa
      - MYSQL_PASSWORD: fiyinfoluwa
    ports:
      - "3306:3306"
    volumes:
      - mysql_data: /var/lib/mysql
    healthcheck:
      test: ["cmd", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: dtq-redis
    restart: always
    ports: -"6379:6379"
    volumes:
      -redis_data: /data
    healthcheck:
      test: ["cmd", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  prometheus:
    image: prom/prometheus:latest
    container_name: dtq-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data: /prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
  grafana:
    image: grafana/grafana:latest
    container_name: dtq-grafana
    restart: always
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  mysql_data:
  redis_data:
  prometheus_data:
  grafana_data:
