version: "3.8"
services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=dtq
    ports: -["3306:3306"]
    volumes: -['./mysql-data:/var/lib/mysql']

  redis:
    image: redis:7-alpine
    ports: -["6379:6379"]
  api:
    build: ../api
    ports: ["3000:3000"]
    depends_on: [mysql, redis]
    env_file: .env
  workers:
    build: ../workers
    depends_on:
      - [redis, mysql]
    deploy:
      replicas: 1
  scheduler:
    build: ../scheduler
    depends_on:
      - [api]
